# Cloud Build configuration for Samurai Insurance Backend - STAGING
# Triggered by commits to the 'dev' branch
# Deploys to an isolated staging environment

substitutions:
  _SERVICE_NAME: backend-staging
  _REGION: us-east5
  _ARTIFACT_REPO: cloud-run-source-deploy
  _IMAGE_NAME: samurai-backend-staging

steps:
  # Step 1: Build the container image with staging tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$BRANCH_NAME'
      - '--build-arg'
      - 'NODE_ENV=staging'
      - '.'
    dir: 'backend'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}'
    waitFor: ['build']

  # Step 3: Deploy container image to Cloud Run staging service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      # Use the same service account as production (or create a staging-specific one)
      - '--service-account'
      - 'si-app-backend-sa@$PROJECT_ID.iam.gserviceaccount.com'
      # Staging environment variables
      - '--update-env-vars'
      - 'NODE_ENV=staging,GOOGLE_PROJECT_ID=$PROJECT_ID,GOOGLE_DATA_STORE_ID=si-data-connector_1764794221917_gcs_store,GCS_BUCKET_NAME=samurai-insurance-app'
      # SECURITY: Reference STAGING secrets from Secret Manager
      - '--update-secrets'
      - 'SUPABASE_URL=supabase-url-staging:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key-staging:latest,SUPABASE_PUBLISHABLE_KEY=supabase-publishable-key-staging:latest'
      # Resource limits (can be lower for staging to save costs)
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      # Lower concurrency/instances for staging
      - '--concurrency'
      - '40'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      # Request timeout
      - '--timeout'
      - '300'
      # Allow unauthenticated for frontend access
      - '--allow-unauthenticated'
      # Add staging label for identification
      - '--labels'
      - 'environment=staging,branch=$BRANCH_NAME'
    waitFor: ['push']

  # Step 4: Output the staging URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-url'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STAGING DEPLOYMENT COMPLETE"
        echo "=========================================="
        gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)' \
          --project=$PROJECT_ID
        echo "=========================================="
    waitFor: ['deploy']

# Container images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$BRANCH_NAME'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # Faster builds with higher machine type (optional)
  machineType: 'E2_HIGHCPU_8'

# Build timeout (10 minutes should be sufficient)
timeout: '600s'

# Tags for filtering builds in Cloud Console
tags:
  - 'staging'
  - 'samurai-insurance'
  - 'backend'
